server:
  address: 0.0.0.0 # Esto asegurará que el servidor escuche en todas las interfaces de red
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true
