# application.yml
server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres
    username: postgres.vxhygzmdcspljvvkawky
    password: zIqfZurS0TmYknkL
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true

security:
  jwt:
    key:
      private: Rd7yFqUFlUqy4HMNT6HzT0jN9tMRSv9Q
    user:
      generator: JWT-IOT_GARAJE