### Probar endpoint:
POST http://localhost:8080/api/v1/vehicles/register
Content-Type: application/json

{
  "licensePlate": "1234AVD",
  "carBranch": "Toyota2",
  "carModel": "Corolla2",
  "carColor": "Rojo",
  "carManufacturingDate":"2024",
  "idUsers": 1

}
### Probar endpoint:
GET http://localhost:8080/api/v1/vehicles

### Probar endpoint:
GET http://localhost:8080/api/v1/vehicles/1/vehicles
